/**
 * Quick Demo/Testing Utilities
 * Use these to test the application without real API keys
 */

import { CulturalResource, ResourceCategory, ResourceSource } from '@/lib/types';

/**
 * Generate mock resources for demonstration
 * Use when API keys are not configured
 */
export function generateMockResources(): CulturalResource[] {
  return [
    {
      id: 'mock-1',
      name: 'Indian Cultural Association',
      category: ResourceCategory.CULTURAL_CLUB,
      description: 'A vibrant community dedicated to celebrating Indian culture, traditions, and festivals. Hosts weekly meetups, workshops, and cultural performances.',
      address: '123 Main Street, Boston, MA 02108',
      latitude: 42.3601,
      longitude: -71.0589,
      phoneNumber: '(617) 555-0101',
      website: 'https://www.indiancultureassociation.org',
      email: 'info@indiancultureassociation.org',
      distance: 2.3,
      rating: 4.8,
      reviewCount: 142,
      credibilityScore: 92,
      source: ResourceSource.GOOGLE_PLACES,
      sourceUrl: 'https://www.google.com/maps/place/Indian+Cultural+Association',
      tags: ['cultural_club', 'student_organization', 'community', 'verified', 'hindi', 'gujarati', 'tamil'],
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-2',
      name: 'Maharaja Indian Restaurant',
      category: ResourceCategory.RESTAURANT,
      description: 'Authentic Indian cuisine with vegetarian and vegan options available. North and South Indian specialties. Serves dosas, curries, breads.',
      address: '456 Newbury Street, Boston, MA 02115',
      latitude: 42.3517,
      longitude: -71.0816,
      phoneNumber: '(617) 555-0202',
      website: 'https://www.maharajaboston.com',
      distance: 1.8,
      rating: 4.6,
      reviewCount: 387,
      credibilityScore: 88,
      source: ResourceSource.GOOGLE_PLACES,
      sourceUrl: 'https://www.google.com/maps/place/Maharaja+Restaurant',
      tags: ['restaurant', 'vegetarian', 'indian_food', 'dining', 'vegan'],
      hours: {
        monday: '11:00 AM - 10:00 PM',
        tuesday: '11:00 AM - 10:00 PM',
        wednesday: '11:00 AM - 10:00 PM',
        thursday: '11:00 AM - 10:00 PM',
        friday: '11:00 AM - 11:00 PM',
        saturday: '11:00 AM - 11:00 PM',
        sunday: '12:00 PM - 10:00 PM',
      },
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-3',
      name: 'Boston Hindu Temple',
      category: ResourceCategory.PLACE_OF_WORSHIP,
      description: 'Sri Venkateswara Hindu Temple serving the Hindu community in Greater Boston. Hosts pujas, spiritual classes, and cultural events.',
      address: '789 Oak Avenue, Wilmington, MA 01887',
      latitude: 42.3521,
      longitude: -71.1482,
      phoneNumber: '(978) 555-0303',
      website: 'https://www.bostonhindutemple.org',
      email: 'inquiries@bostonhindutemple.org',
      distance: 8.5,
      rating: 4.9,
      reviewCount: 201,
      credibilityScore: 95,
      source: ResourceSource.GOOGLE_PLACES,
      sourceUrl: 'https://www.google.com/maps/place/Boston+Hindu+Temple',
      tags: ['place_of_worship', 'temple', 'hindu', 'spiritual', 'yoga', 'meditation'],
      hours: {
        monday: '4:00 PM - 8:00 PM',
        tuesday: '4:00 PM - 8:00 PM',
        wednesday: '4:00 PM - 8:00 PM',
        thursday: '4:00 PM - 8:00 PM',
        friday: '4:00 PM - 8:00 PM',
        saturday: '9:00 AM - 8:00 PM',
        sunday: '9:00 AM - 2:00 PM',
      },
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-4',
      name: 'Diwali Festival 2026',
      category: ResourceCategory.EVENT,
      description: 'Celebrate Diwali with us! Light, music, food, and cultural performances. Traditional dances, fireworks, food stalls, and shopping.',
      address: 'Boston Common, Boston, MA 02108',
      website: 'https://www.eventbrite.com/e/diwali-festival-2026',
      credibilityScore: 85,
      source: ResourceSource.EVENTBRITE,
      sourceUrl: 'https://www.eventbrite.com/e/diwali-festival-2026',
      tags: ['event', 'festival', 'diwali', 'cultural celebration', 'free_event'],
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-5',
      name: 'India Market & Grocery',
      category: ResourceCategory.GROCERY_STORE,
      description: 'Import spices, groceries, and ingredients for Indian cuisine. Fresh produce, Indian sweets, basmati rice, lentils, and specialty items.',
      address: '321 Harvard Street, Brookline, MA 02446',
      latitude: 42.3317,
      longitude: -71.1046,
      phoneNumber: '(617) 555-0505',
      distance: 4.2,
      rating: 4.7,
      reviewCount: 156,
      credibilityScore: 84,
      source: ResourceSource.GOOGLE_PLACES,
      sourceUrl: 'https://www.google.com/maps/place/India+Market',
      tags: ['grocery_store', 'asian_market', 'spices', 'food', 'organic'],
      hours: {
        monday: '9:00 AM - 8:00 PM',
        tuesday: '9:00 AM - 8:00 PM',
        wednesday: '9:00 AM - 8:00 PM',
        thursday: '9:00 AM - 8:00 PM',
        friday: '9:00 AM - 8:00 PM',
        saturday: '9:00 AM - 9:00 PM',
        sunday: '10:00 AM - 8:00 PM',
      },
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-6',
      name: 'Harvard Hindi Language Club',
      category: ResourceCategory.LANGUAGE_CLASS,
      description: 'A student organization dedicated to learning and practicing the Hindi language. Weekly conversations, grammar classes, and cultural immersion.',
      website: 'https://www.harvard.edu/student-organizations',
      credibilityScore: 93,
      source: ResourceSource.UNIVERSITY,
      sourceUrl: 'https://www.harvard.edu/student-organizations',
      tags: ['university', 'language_club', 'student_organization', 'verified', 'hindi'],
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-7',
      name: 'South Asian Youth Network',
      category: ResourceCategory.MEETUP_GROUP,
      description: 'Professional networking and social group for young South Asians. Monthly meetups, workshops, and career development events.',
      address: '200 Berkeley Street, Boston, MA 02116',
      latitude: 42.3458,
      longitude: -71.0776,
      phoneNumber: '(617) 555-0707',
      website: 'https://www.sayn.org',
      distance: 3.5,
      rating: 4.5,
      reviewCount: 89,
      credibilityScore: 81,
      source: ResourceSource.MEETUP,
      sourceUrl: 'https://www.meetup.com/south-asian-youth',
      tags: ['meetup', 'networking', 'professional', 'community', 'young_professionals'],
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-8',
      name: 'Kathak Dance Classes',
      category: ResourceCategory.CULTURAL_CENTER,
      description: 'Learn classical Indian Kathak dance. Classes for beginners to advanced. Taught by certified instructors trained in India.',
      address: '150 Hanover Street, Boston, MA 02109',
      latitude: 42.3629,
      longitude: -71.0566,
      phoneNumber: '(617) 555-0808',
      email: 'classes@kathakboston.org',
      distance: 1.2,
      rating: 4.9,
      reviewCount: 67,
      credibilityScore: 90,
      source: ResourceSource.GOOGLE_PLACES,
      sourceUrl: 'https://www.google.com/maps/place/Kathak+Dance+Classes',
      tags: ['cultural_center', 'dance', 'arts', 'education', 'traditional'],
      hours: {
        monday: '5:00 PM - 7:00 PM',
        tuesday: '5:00 PM - 7:00 PM',
        wednesday: '5:00 PM - 7:00 PM',
        thursday: '5:00 PM - 7:00 PM',
        friday: '6:00 PM - 8:00 PM',
        saturday: '10:00 AM - 12:00 PM',
        sunday: 'Closed',
      },
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-9',
      name: 'Namaste Yoga and Wellness',
      category: ResourceCategory.CULTURAL_CENTER,
      description: 'Traditional yoga classes inspired by Indian practices. Hatha, Vinyasa, and Kundalini yoga. Meditation and breathing workshops.',
      address: '99 Tremont Street, Boston, MA 02108',
      latitude: 42.3584,
      longitude: -71.0613,
      phoneNumber: '(617) 555-0909',
      website: 'https://www.namastetoyoga.com',
      distance: 2.1,
      rating: 4.8,
      reviewCount: 234,
      credibilityScore: 89,
      source: ResourceSource.GOOGLE_PLACES,
      sourceUrl: 'https://www.google.com/maps/place/Namaste+Yoga',
      tags: ['wellness', 'yoga', 'meditation', 'spiritual', 'health'],
      hours: {
        monday: '6:00 AM - 8:00 PM',
        tuesday: '6:00 AM - 8:00 PM',
        wednesday: '6:00 AM - 8:00 PM',
        thursday: '6:00 AM - 8:00 PM',
        friday: '6:00 AM - 7:00 PM',
        saturday: '9:00 AM - 5:00 PM',
        sunday: '9:00 AM - 4:00 PM',
      },
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-10',
      name: 'Indian Islamic Center',
      category: ResourceCategory.PLACE_OF_WORSHIP,
      description: 'Mosque serving the Indian Muslim community. Offers Jumu\'ah prayers, community dinners, and Islamic education programs.',
      address: '500 Washington Street, Boston, MA 02111',
      latitude: 42.3469,
      longitude: -71.0568,
      phoneNumber: '(617) 555-1010',
      website: 'https://www.bostonislamiccenter.org',
      distance: 3.8,
      rating: 4.7,
      reviewCount: 124,
      credibilityScore: 87,
      source: ResourceSource.GOOGLE_PLACES,
      sourceUrl: 'https://www.google.com/maps/place/Islamic+Center',
      tags: ['place_of_worship', 'mosque', 'muslim', 'spiritual', 'community'],
      hours: {
        monday: 'Friday: 1:00 PM - 2:00 PM',
        tuesday: 'Daily: 5 prayer times',
        wednesday: '',
        thursday: '',
        friday: '1:00 PM - 2:00 PM',
        saturday: '',
        sunday: '',
      },
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-11',
      name: 'Bollywood Dance Night',
      category: ResourceCategory.EVENT,
      description: 'Join us for Bollywood movie night with music, dancing, and snacks! Monthly event featuring popular Bollywood films and themed parties.',
      address: '777 Commonwealth Avenue, Boston, MA 02215',
      website: 'https://www.eventbrite.com/e/bollywood-dance-night',
      credibilityScore: 82,
      source: ResourceSource.EVENTBRITE,
      sourceUrl: 'https://www.eventbrite.com/e/bollywood-night',
      tags: ['event', 'entertainment', 'dance', 'movies', 'social'],
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-12',
      name: 'Hindi Literature Circle',
      category: ResourceCategory.ASSOCIATION,
      description: 'Monthly gathering for Hindi literature enthusiasts. Discuss classic and contemporary Hindi authors, poetry readings, and cultural insights.',
      address: '250 Huntington Avenue, Boston, MA 02115',
      latitude: 42.3425,
      longitude: -71.0878,
      phoneNumber: '(617) 555-1212',
      distance: 5.2,
      rating: 4.6,
      reviewCount: 45,
      credibilityScore: 79,
      source: ResourceSource.MEETUP,
      sourceUrl: 'https://www.meetup.com/hindi-literature',
      tags: ['association', 'literature', 'culture', 'community', 'language', 'indian'],
      isVerified: true,
      lastUpdated: new Date(),
    },    {
      id: 'mock-16',
      name: 'East Asian Student Union',
      category: ResourceCategory.CULTURAL_CLUB,
      description: 'Supports students with East Asian cultural interests, including language exchange and heritage events.',
      address: '470 Comm Ave, Boston, MA 02115',
      latitude: 42.3504,
      longitude: -71.1260,
      phoneNumber: '(617) 555-1616',
      distance: 1.9,
      rating: 4.5,
      reviewCount: 64,
      credibilityScore: 83,
      source: ResourceSource.UNIVERSITY,
      sourceUrl: 'https://www.university.edu/east-asian-student-union',
      tags: ['cultural_club', 'east asian', 'chinese', 'korean', 'japanese'],
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-17',
      name: 'Lunar New Year Parade',
      category: ResourceCategory.EVENT,
      description: 'Annual Lunar New Year celebration with parade, cultural performances, and food stalls.',
      address: 'Chinatown Gate, Boston, MA 02111',
      website: 'https://www.bostonchinatown.com/lunar-new-year',
      credibilityScore: 90,
      source: ResourceSource.EVENTBRITE,
      sourceUrl: 'https://www.eventbrite.com/e/lunar-new-year-parade',
      tags: ['event', 'east asian', 'lunar new year', 'festival', 'chinese'],
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-18',
      name: 'Jade Buddha Temple',
      category: ResourceCategory.PLACE_OF_WORSHIP,
      description: 'East Asian spiritual center and meditation space offering public ceremonies and cultural learning.',
      address: '1 Harrison Ave, Boston, MA 02111',
      latitude: 42.3535,
      longitude: -71.0615,
      phoneNumber: '(617) 555-1818',
      distance: 0.5,
      rating: 4.6,
      reviewCount: 111,
      credibilityScore: 87,
      source: ResourceSource.GOOGLE_PLACES,
      sourceUrl: 'https://www.google.com/maps/place/Jade+Buddha+Temple',
      tags: ['place_of_worship', 'east asian', 'buddhism', 'culture'],
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-19',
      name: 'Middle Eastern Student Association',
      category: ResourceCategory.CULTURAL_CLUB,
      description: 'Campus group focused on Middle Eastern cultural events and community networking.',
      address: '45 Bay State Rd, Boston, MA 02215',
      latitude: 42.3496,
      longitude: -71.1078,
      phoneNumber: '(617) 555-1919',
      distance: 1.7,
      rating: 4.4,
      reviewCount: 58,
      credibilityScore: 82,
      source: ResourceSource.UNIVERSITY,
      sourceUrl: 'https://www.university.edu/middle-eastern-student-association',
      tags: ['cultural_club', 'middle eastern', 'arab', 'muslim', 'community'],
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-20',
      name: 'Middle Eastern Food Festival',
      category: ResourceCategory.EVENT,
      description: 'Taste regional foods from Lebanon, Iran, Turkey and more in a cultural fair.',
      address: '200 Mass Ave, Boston, MA 02115',
      website: 'https://www.eventbrite.com/e/middle-eastern-food-festival',
      credibilityScore: 86,
      source: ResourceSource.EVENTBRITE,
      sourceUrl: 'https://www.eventbrite.com/e/middle-eastern-food-festival',
      tags: ['event', 'middle eastern', 'food', 'culture', 'festival'],
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-21',
      name: 'Latin American Student Alliance',
      category: ResourceCategory.CULTURAL_CLUB,
      description: 'Club celebrating Latin American music, dance, food, and community events.',
      address: '100 Bay State Rd, Boston, MA 02215',
      latitude: 42.3472,
      longitude: -71.1064,
      phoneNumber: '(617) 555-2121',
      distance: 2.0,
      rating: 4.7,
      reviewCount: 70,
      credibilityScore: 84,
      source: ResourceSource.UNIVERSITY,
      sourceUrl: 'https://www.university.edu/latin-american-student-alliance',
      tags: ['cultural_club', 'latin american', 'hispanic', 'community'],
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-22',
      name: 'Latin Fiesta and Dance Night',
      category: ResourceCategory.EVENT,
      description: 'Salsa, Merengue, and Reggaeton music with dance lessons and cultural food stalls.',
      address: '15 Brookline Ave, Boston, MA 02215',
      website: 'https://www.eventbrite.com/e/latin-fiesta-dance-night',
      credibilityScore: 83,
      source: ResourceSource.EVENTBRITE,
      sourceUrl: 'https://www.eventbrite.com/e/latin-fiesta-dance-night',
      tags: ['event', 'latin american', 'dance', 'culture'],
      isVerified: true,
      lastUpdated: new Date(),
    },    {
      id: 'mock-13',
      name: 'North American Heritage Club',
      category: ResourceCategory.CULTURAL_CLUB,
      description: 'Students exploring North American folk traditions, Indigenous history, and modern cultural exchange.',
      address: '111 Commonwealth Ave, Boston, MA 02115',
      latitude: 42.3510,
      longitude: -71.0790,
      phoneNumber: '(617) 555-1313',
      distance: 1.4,
      rating: 4.5,
      reviewCount: 72,
      credibilityScore: 83,
      source: ResourceSource.UNIVERSITY,
      sourceUrl: 'https://www.university.edu/north-american-heritage',
      tags: ['cultural_club', 'north american', 'american', 'indigenous', 'community'],
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-14',
      name: 'Boston African Heritage Center',
      category: ResourceCategory.CULTURAL_CENTER,
      description: 'Celebrates African diasporic heritage through music, arts, and education.',
      address: '222 Tremont St, Boston, MA 02116',
      latitude: 42.3473,
      longitude: -71.0697,
      phoneNumber: '(617) 555-1414',
      distance: 2.7,
      rating: 4.7,
      reviewCount: 110,
      credibilityScore: 85,
      source: ResourceSource.GOOGLE_PLACES,
      sourceUrl: 'https://www.bostonafricanheritage.org',
      tags: ['cultural_center', 'african', 'diaspora', 'arts', 'community'],
      isVerified: true,
      lastUpdated: new Date(),
    },
    {
      id: 'mock-15',
      name: 'African Diaspora Music Night',
      category: ResourceCategory.EVENT,
      description: 'Live African music and dance experience with local artists and authentic food vendors.',
      address: '33 Chinatown Park, Boston, MA 02111',
      website: 'https://www.eventbrite.com/e/african-diaspora-music-night',
      credibilityScore: 80,
      source: ResourceSource.EVENTBRITE,
      sourceUrl: 'https://www.eventbrite.com/e/african-diaspora-music-night',
      tags: ['event', 'african', 'music', 'culture', 'celebration'],
      isVerified: true,
      lastUpdated: new Date(),
    },
  ];
}
